github:
  description: "Docker packaging for Apache Flink"
  homepage: https://flink.apache.org/
  labels:
    - flink
    - docker
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
